# This file is not used anymore and is left for reference. 
name: Elastic Dev Docs Builder (Deprecated)
on:
  workflow_call:
    secrets:
      VERCEL_GITHUB_TOKEN:
        description: 'A GitHub PAT with repo scope'
        required: true
      VERCEL_TOKEN:
        description: 'Vercel API token, account level'
        required: true
      VERCEL_ORG_ID:
        description: 'Vercel ORG token, org level'
        required: true
      VERCEL_PROJECT_ID_DOCS_DEV:
        description: 'Vercel PROJECT token, project level'
        required: true
  pull_request_target:
    paths:
      - '**.mdx'
      - '**.docnav.json'
      - '**.docapi.json'
      - '**.devdocs.json'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.gif'
    types: [closed, opened, synchronize, reopened]

jobs:
  build-dev-docs:
    name: Build internal docs
    runs-on: ubuntu-latest
    steps:
      - name: Setup workspace
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Checkout current branch into temp
        if: github.event.pull_request.merged == false
        uses: actions/checkout@v3
        with:
          path: 'temp'
          fetch-depth: 2
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          persist-credentials: false

      - name: Checkout current branch into temp
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v3
        with:
          path: 'temp'
          persist-credentials: false

      - name: Checkout essential repos
        uses: actions/checkout@v3
        with:
          repository: elastic/docs.elastic.dev
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/docs.elastic.dev
          persist-credentials: false

      - name: Checkout Wordlake
        uses: actions/checkout@v3
        with:
          repository: elastic/wordlake-dev
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/wordlake-dev
          persist-credentials: false

      - name: Temp sources override
        shell: bash
        run: cp -f ${{ github.workspace }}/wordlake-dev/.scaffold/content.js ${{ github.workspace }}/docs.elastic.dev/config/.

      - name: Show workspace
        shell: bash
        run: ls -lat ${{ github.workspace }}

      - name: Portal
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/wordlake-dev/${{ github.event.repository.name }}
          rm -rf ${{ github.workspace }}/wordlake-dev/${{ github.event.repository.name }}/*
          rsync --ignore-missing-args -zavpm --no-l \
          --exclude='cats.mdx' \
          --exclude='infrastructure/ansible/systests/*' \
          --include='*.docnav.json' \
          --include='*.apidocs.json' \
          --include='*.mdx' \
          --include='*.png' \
          --include='*.gif' \
          --include='*.jpg' \
          --include='*.jpeg' \
          --include='*.devdocs.json' \
          --include='*/' \
          --exclude='*' \
          ${{ github.workspace }}/temp/ \
          ${{ github.workspace }}/wordlake-dev/${{ github.event.repository.name }}/

      - name: Generate preview
        if: github.event.pull_request.merged == false
        uses: elastic/builder@v21.3.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_DOCS_DEV }} #Required
          vercel-project-name: docs-elastic-dev
          working-directory: ./
          github-comment: false # Otherwise need github-token (VERCEL_GITHUB_TOKEN)

      - name: Portal for deploy
        if: github.event.pull_request.merged == true
        shell: bash
        run: |
          cd ${{ github.workspace }}/wordlake-dev
          git config user.name count-docula
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "New content from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          git push
